runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  DATABASE_URL: 'postgresql://ucmdl7jh4u14ts:p3c6d44f1bbd7d3bbf90a6d59ccec442290a1f0ba094e87a01d42ba918ccff95f@c6sfjnr30ch74e.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dfrtsiuh6hilvi'

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
