runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  DATABASE_URL: "your-database-url"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
